import * as cheerio from 'cheerio';
import {loadDb,saveDb,upsert} from './db.js';
export const SOURCE='https://donghualife.com/';
const UA='Mozilla/5.0 (compatible; DonghuaFlixSync/2.0; +https://donghualife.com/)';
const abs=(href,base=SOURCE)=>{try{if(!href||/^javascript:|^mailto:/i.test(href))return null;return new URL(href,base).href}catch{return null}};
const clean=s=>(s||'').replace(/\s+/g,' ').trim();
const slug=url=>{try{return new URL(url).pathname.split('/').filter(Boolean).pop()||''}catch{return ''}};
const unique=a=>[...new Set(a.filter(Boolean))];
const sourceUrl=u=>new URL(u).origin+new URL(u).pathname;
export async function fetchHtml(url){const r=await fetch(url,{headers:{'User-Agent':UA,'Accept-Language':'es-ES,es;q=0.9,en;q=0.7'},redirect:'follow'});if(!r.ok)throw new Error(`${r.status} ${url}`);return r.text()}
function imageOf($,base){const src=$('meta[property="og:image"]').attr('content')||$('meta[name="twitter:image"]').attr('content')||$('img').first().attr('src')||$('img').first().attr('data-src');return abs(src,base)}
function links($,selector,base){const out=[];$(selector).each((_,e)=>{const h=abs($(e).attr('href'),base);if(h&&new URL(h).hostname===new URL(base).hostname)out.push(sourceUrl(h))});return unique(out)}
function bodyText($){return clean($('body').text())}
function labelValue($,label,nextLabels=[]){const text=bodyText($);const stop=nextLabels.map(x=>x.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|');const re=new RegExp(label.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\s*:?[\\s]*([\\s\\S]*?)(?='+ (stop?'(?:'+stop+')':'$') + '|$)','i');return clean(text.match(re)?.[1]||'')}
function detectGenres($){const known=['Animación','Cultivo','Acción','Aventura','Artes marciales','Comedia','Drama','Romance','Reencarnación','Isekai','Estrategia','Fantasía','Misterio','Horror','Historia','Ciencia ficción','Venganza','Sistema de cultivo','Superpoderes','Escolar','Sobrenatural'];const out=[];$('a').each((_,e)=>{const t=clean($(e).text());if(known.some(g=>g.toLowerCase()===t.toLowerCase()))out.push(t)});return unique(out)}
export function parseSeries(html,url){const $=cheerio.load(html);const title=clean($('h1').first().text()||$('h2').first().text()||$('title').text()).replace(/\s*\|.*$/,'');const text=bodyText($);const original=labelValue($,'Título original',['Duración','Estado']);const duration=labelValue($,'Duración',['Estado','Fecha de emisión']);const status=clean($('a').filter((_,e)=>/en emisión|finalizado|en pausa/i.test($(e).text())).first().text())||labelValue($,'Estado',['Fecha de emisión']);const release=labelValue($,'Fecha de emisión',['Género','Synopsis','Sinopsis']);let synopsis='';const idx=text.search(/Synopsis\s+|Sinopsis\s+/i);if(idx>=0){synopsis=clean(text.slice(idx).replace(/^(Synopsis|Sinopsis)\s*/i,'').split(/\s+(?:Temporadas|Autor|Studio|Estudio)\s+/i)[0])}const seasonUrls=links($,'a[href*="/season/"]',url);return{id:slug(url),slug:slug(url),title,originalTitle:original||null,duration:duration||null,status:status||null,releaseDate:release||null,synopsis:synopsis||null,image:imageOf($,url),sourceUrl:url,genres:detectGenres($),seasonUrls,updatedAt:new Date().toISOString()}}
export function parseSeason(html,url){const $=cheerio.load(html);const title=clean($('h1').first().text()||$('h2').first().text()||$('title').text());const episodeLinks=[];$('a[href*="/episode/"]').each((_,e)=>{const href=abs($(e).attr('href'),url);if(!href)return;const row=$(e).closest('tr');const cells=row.find('td').map((_,c)=>clean($(c).text())).get();const txt=clean($(e).text());const n=(cells[0]||txt).match(/\d+/)?.[0]||null;const date=cells.find(x=>/\d{4}|enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre/i.test(x))||null;episodeLinks.push({url:sourceUrl(href),number:n?Number(n):null,title:txt||`Episodio ${n||''}`.trim(),releaseDate:date})});return{id:slug(url),slug:slug(url),title,sourceUrl:url,image:imageOf($,url),episodeLinks:[...new Map(episodeLinks.map(x=>[x.url,x])).values()]}}
function hostName(u){try{return new URL(u).hostname.replace(/^www\./,'')}catch{return'Servidor'}}
function addServer(arr,name,url,embed=false){if(!url)return;const key=(name+'|'+url).toLowerCase();if(!arr.some(x=>(x.name+'|'+x.url).toLowerCase()===key))arr.push({name:name||hostName(url),url,embed})}
export function parseEpisode(html,url){const $=cheerio.load(html);const title=clean($('h1').first().text()||$('title').text());const servers=[];$('a').each((_,e)=>{const name=clean($(e).text());const href=abs($(e).attr('href'),url);if(href&&name&&/rumble|dailymotion|youtube|ok\.ru|stream|vidoza|filemoon|voe|mixdrop|mega|mp4upload|vidmoly|sibnet/i.test(name+' '+href))addServer(servers,name,href,false)});$('iframe,video source').each((_,e)=>{const src=abs($(e).attr('src')||$(e).attr('data-src'),url);if(src)addServer(servers,hostName(src),src,true)});const previousUrl=abs($('a').filter((_,e)=>/Anterior/i.test($(e).text())).attr('href'),url);const nextUrl=abs($('a').filter((_,e)=>/Siguiente/i.test($(e).text())).attr('href'),url);return{id:slug(url),slug:slug(url),title,sourceUrl:url,servers,previousUrl:previousUrl?sourceUrl(previousUrl):null,nextUrl:nextUrl?sourceUrl(nextUrl):null,updatedAt:new Date().toISOString()}}
function movieFromLink($,e,base){const url=abs($(e).attr('href'),base);if(!url)return null;const title=clean($(e).text());if(!title)return null;return{id:slug(url),slug:slug(url),title,sourceUrl:sourceUrl(url),image:abs($(e).closest('article,.views-row,.card').find('img').first().attr('src'),base),updatedAt:new Date().toISOString()}}
export async function syncAll({onProgress=()=>{}}={}){const db=await loadDb();const startedAt=new Date().toISOString();db.meta.lastSync={status:'running',startedAt,finishedAt:null,error:null};await saveDb(db);try{const seeds=[SOURCE+'',SOURCE+'donghuas',SOURCE+'en-emision',SOURCE+'finalizado',SOURCE+'en-pausa',SOURCE+'movies'];const seriesUrls=new Set();const movieUrls=new Set();for(const seed of seeds){try{const h=await fetchHtml(seed);const $=cheerio.load(h);links($,'a[href*="/series/"]',seed).forEach(u=>seriesUrls.add(u));links($,'a[href*="/movies/"]',seed).forEach(u=>movieUrls.add(u));links($,'a[href*="/movie/"]',seed).forEach(u=>movieUrls.add(u));onProgress(`Fuente: ${seed}`)}catch(e){onProgress(`Fuente omitida: ${e.message}`)}}for(const u of seriesUrls){try{const s=parseSeries(await fetchHtml(u),u);upsert(db.series,s);for(const g of s.genres)if(!db.genres.includes(g))db.genres.push(g);onProgress(`Serie ${s.title}`);for(const su of s.seasonUrls){try{const season=parseSeason(await fetchHtml(su),su);season.seriesId=s.id;upsert(db.seasons,season);for(const e of season.episodeLinks){try{const ep=parseEpisode(await fetchHtml(e.url),e.url);Object.assign(ep,{seriesId:s.id,seasonId:season.id,number:e.number,releaseDate:e.releaseDate});upsert(db.episodes,ep)}catch(err){onProgress(`Episodio omitido: ${err.message}`)}}}catch(err){onProgress(`Temporada omitida: ${err.message}`)}}}catch(e){onProgress(`Serie omitida: ${e.message}`)}}for(const u of movieUrls){try{const h=await fetchHtml(u);const $=cheerio.load(h);const title=clean($('h1').first().text()||$('title').text());upsert(db.movies,{id:slug(u),slug:slug(u),title,sourceUrl:u,image:imageOf($,u),htmlUpdatedAt:new Date().toISOString()})}catch{}}db.meta.syncedAt=new Date().toISOString();db.meta.lastSync={status:'success',startedAt,finishedAt:db.meta.syncedAt,error:null};await saveDb(db);return db}catch(e){db.meta.lastSync={status:'error',startedAt,finishedAt:new Date().toISOString(),error:e.message};await saveDb(db);throw e}}
